version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true

    ports:
      - 9200:9200
      - 9600:9600

#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:2.9.0
#    environment:
#      - OPENSEARCH_HOSTS=http://opensearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - opensearch
